name: snap
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.SNAPSTORE_LOGIN }}
    with:
      snap-risk: candidate
      snap-test-script: |
        #!/bin/bash

        x2cli --help

        x2cli map
        ls -la mapcli
